// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfukKJpYMR-TmZskdtkLdg7_RcHVEcyTw',
    appId: '1:360409925144:web:30fa48697566584716a56d',
    messagingSenderId: '360409925144',
    projectId: 'hack-281ca',
    authDomain: 'hack-281ca.firebaseapp.com',
    storageBucket: 'hack-281ca.firebasestorage.app',
    measurementId: 'G-Y506TSRBDS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQWKYGbKGYxrLWrccS-9TwEtaSLxbjzg',
    appId: '1:360409925144:android:96bc92451b02593316a56d',
    messagingSenderId: '360409925144',
    projectId: 'hack-281ca',
    storageBucket: 'hack-281ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7lXt8NDsfS8g4x_RFL0vybiQ-O6ikAGo',
    appId: '1:360409925144:ios:75a1ca78c858494c16a56d',
    messagingSenderId: '360409925144',
    projectId: 'hack-281ca',
    storageBucket: 'hack-281ca.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7lXt8NDsfS8g4x_RFL0vybiQ-O6ikAGo',
    appId: '1:360409925144:ios:75a1ca78c858494c16a56d',
    messagingSenderId: '360409925144',
    projectId: 'hack-281ca',
    storageBucket: 'hack-281ca.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfukKJpYMR-TmZskdtkLdg7_RcHVEcyTw',
    appId: '1:360409925144:web:43aa92153c6ae9cc16a56d',
    messagingSenderId: '360409925144',
    projectId: 'hack-281ca',
    authDomain: 'hack-281ca.firebaseapp.com',
    storageBucket: 'hack-281ca.firebasestorage.app',
    measurementId: 'G-RDGB8VZLGF',
  );

}